# Generated by Django 3.1.5 on 2021-01-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categorias_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nome_categoria',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
