# Generated by Django 3.1.5 on 2021-01-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categorias_criado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='nome',
            new_name='nome_categoria',
        ),
    ]
