name: Company Hero Test Integration
on:
  pull_request:
    branches: [ main ]
jobs:
  scanapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run automated API tests
        uses: scanapi/github-action@v1
        with:
          arguments: "run ./scanapi/company_hero.yaml"
      - name: Upload scanapi-report.html
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ScanAPI Report
          path: scanapi-report.html